version: '3.3'

services:
  examples-jpa-postgres:
    image: postgres
    restart: always
    container_name: examples-jpa-postgres-container
    environment:
      - PGDATA=/var/lib/postgresql/data/examples
      - POSTGRES_DB=selectel
      - POSTGRES_USER=selectel
      - POSTGRES_PASSWORD=selectel
    volumes:
      - /var/lib/docker/volumes/examples/jpa/postgres/:/var/lib/postgresql/data/examples
      - ./sql_scripts/0.schemas.sql:/docker-entrypoint-initdb.d/0.schemas.sql
      - ./sql_scripts/1.example.sql:/docker-entrypoint-initdb.d/1.example.sql
      - ./sql_scripts/2.example.sql:/docker-entrypoint-initdb.d/2.example.sql
      - ./sql_scripts/4.example.sql:/docker-entrypoint-initdb.d/4.example.sql
    ports:
      - 5432:5432
