version: '3.3'

services:
  ${POSTGRES_SERVICE_NAME}:
    image: postgres
    restart: always
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - PGDATA=${CONTAINER_POSTGRES_DATA}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${HOST_POSTGRES_VOLUME_PATH}:${CONTAINER_POSTGRES_DATA}
      - ${POSTGRES_INIT_SCRIPTS_0}:${CONTAINER_POSTGRES_INIT_SCRIPTS_0}
      - ${POSTGRES_INIT_SCRIPTS_1}:${CONTAINER_POSTGRES_INIT_SCRIPTS_1}
      - ${POSTGRES_INIT_SCRIPTS_2}:${CONTAINER_POSTGRES_INIT_SCRIPTS_2}
      - ${POSTGRES_INIT_SCRIPTS_4}:${CONTAINER_POSTGRES_INIT_SCRIPTS_4}
    ports:
      - ${POSTGRES_PORT}:${CONTAINER_POSTGRES_PORT}
