package dbms.hibernate.inheritance;

import dbms.hibernate.AutoGeneratedId;
import lombok.Setter;
import lombok.experimental.Accessors;

import javax.persistence.Entity;
import javax.persistence.Table;

public interface MappedSuperclass {
}

@Accessors(chain = true)
@javax.persistence.MappedSuperclass
class Person extends AutoGeneratedId<Long> {
    @Setter
    private String name;
}

@Accessors(chain = true)
@Table(name = "persons")
@Entity
class Employee extends Person {
    @Setter
    private String company;
}

@Accessors(chain = true)
@Table(name = "persons")
@Entity
class CEO extends Employee {
    @Setter
    private String department;
}

