package dbms.hibernate.inheritance;

import dbms.hibernate.AutoGeneratedId;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.hibernate.annotations.DiscriminatorFormula;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

import static dbms.hibernate.inheritance.SingleTableStrategy.PRODUCT_TYPE;

public class SingleTableStrategy {
    public static final String PRODUCT_TYPE = "product_type";
}

@Setter
@Accessors(chain = true)
@Entity
@Table(name="products")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(
    name = PRODUCT_TYPE,
    discriminatorType = DiscriminatorType.INTEGER)
class Product extends AutoGeneratedId<Long> {
    private String name;
}

@Setter
@Accessors(chain = true)
@Entity
@DiscriminatorValue("1")
class Book extends Product {
    private String author;
}

@Setter
@Accessors(chain = true)
@Entity
@DiscriminatorValue("2")
class Pen extends Product {
    private String color;
}

/**
 * Any row without a discriminator value will be mapped to the entity class with this annotation; this can be applied to the root class of the hierarchy.
 */
@Entity
@DiscriminatorValue("null")
class NoDiscriminator extends Product {
    private String value;
}

/**
 *  Any row with a discriminator value not matching any of the ones associated with entity definitions will be mapped to the class with this annotation.
 */
@Entity
@DiscriminatorValue("not null")
class OtherDiscriminator extends Product {
    private String value;
}

/**
 * <p>This strategy has the advantage of polymorphic query performance since only one table needs to be accessed when querying parent entities.
 *
 * <p>On the org.home.other hand, this also means that we can no longer use NOT NULL constraints on subclass entity properties.
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorFormula("case when author is not null then 1 else 2 end")
class ProductByFormula extends AutoGeneratedId<Long> {

}
