package dbms.hibernate.cascade;

import dbms.hibernate.AutoGeneratedId;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.ArrayList;
import java.util.List;

public class EntitiesOneToMany {
}

@Getter
@Setter
@Entity
@Table(name = "players")
@Accessors(chain = true)
class Player extends AutoGeneratedId<Integer> {

    @ManyToOne
    private Team team;

    private String review;
}

@Entity
@Table(name = "teams")
@Accessors(chain = true)
class Team extends AutoGeneratedId<Integer> {

    @Setter
    private String name;

    @Getter
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "team", orphanRemoval = true)
    private List<Player> players = new ArrayList<>();

    public Team addPlayers(Player... players) {
        for (Player p : players) {
            p.setTeam(this);
            this.players.add(p);
        }
        return this;
    }

    public Team removePlayer(Player player) {
        player.setTeam(null);
        this.players.remove(player);
        return this;
    }
}
