package dbms.hibernate.cascade;

import dbms.hibernate.AutoGeneratedId;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.ArrayList;
import java.util.List;

public class EntitiesOneToMany {
}

@Getter
@Setter
@Entity
@Table(name = "players")
class Player extends AutoGeneratedId {

    @ManyToOne
    private Team team;

    private String review;
}

@Entity
@Table(name = "teams")
class Team extends AutoGeneratedId {

    @Setter
    private String name;

    @Getter
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "team", orphanRemoval = true)
    private List<Player> players = new ArrayList<>();

    public void addPlayer(Player player) {
        players.add(player);
        player.setTeam(this);
    }

    public void removePlayer(Player player) {
        player.setTeam(null);
        this.players.remove(player);
    }
}
