package dbms.hibernate.identifiers;

/**
 * <p>This type of generation relies on the IdentityGenerator, which expects values generated by an identity column in the database. This means they are auto-incremented.
 *
 * <p>To use this generation type, we only need to set the strategy parameter:
 * <pre>{@code
 * @Entity
 * public class Student {
 *     @Id
 *     @GeneratedValue (strategy = GenerationType.IDENTITY)
 *     private long studentId;
 * }
 * }</pre>
 * <p>One thing to note is that IDENTITY generation disables batch updates.
 */
public interface Identity {
}
