package dbms.hibernate;

import lombok.Getter;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class AutoGeneratedId {

    @Id
    @Getter
    @GeneratedValue(strategy= GenerationType.AUTO)
    private Long id;
}
