package dbms.hibernate.user_type.ex1;

import dbms.hibernate.user_type.ex1.type.PhoneNumberType;
import dbms.hibernate.user_type.ex1.type.SalaryType;
import dbms.hibernate.AutoGeneratedId;
import lombok.Setter;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.hibernate.annotations.Columns;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.time.LocalDate;

@Setter
@Entity
@TypeDef(name = "PhoneNumber", typeClass = PhoneNumberType.class, defaultForType = PhoneNumber.class)
@Table(name = "office_employee")
public class OfficeEmployee extends AutoGeneratedId<Long> {

    @Column(name = "hired_at")
    @Type(type = "dbms.hibernate.user_type.ex1.type.LocalDateStringType")
    private LocalDate hiredAt;

    @Columns(
        columns = {
            @Column(name = "country_code"),
            @Column(name = "city_code"),
            @Column(name = "number")})
    private PhoneNumber phoneNumber;

    @Columns(
        columns = {
            @Column(name = "address_line_1"),
            @Column(name = "address_line_2"),
            @Column(name = "country"),
            @Column(name = "city"),
            @Column(name = "zipcode")})
    @Type(type = "dbms.hibernate.user_type.ex1.type.AddressType")
    private Address address;


    @Columns(columns = {
        @Column(name = "amount"),
        @Column(name = "currency")})
    @Type(
        type = "dbms.hibernate.user_type.ex1.type.SalaryType",
        parameters = { @Parameter(name = SalaryType.CURRENCY, value = "USD") })
    private Salary salary;

    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("id", id)
            .append("hiredAt", hiredAt)
            .append("phoneNumber", phoneNumber)
            .append("address", address)
            .append("salary", salary)
            .toString();
    }
}

